AWSTemplateFormatVersion: 2010-09-09
Parameters:
 vpcCIDR:
  Type: String
  Default: 10.16.0.0/16
  Description: Vpc Network Range
 VPCName:
  Type: String
  Default: k8s-vpc
  Description: Vpc Name
 privSubnet:
  Type: String
  Default: 10.16.1.0/24
  Description: Private Subnet Range
 pubSubnet:
  Type: String
  Default: 10.16.2.0/24
  Description: Public Subnet Range

Resources:
 vpcK8S:
  Type: AWS::EC2::VPC
  Properties:
   CidrBlock: !Ref vpcCIDR
   EnableDnsSupport: True
   EnableDnsHostnames: True
   Tags:
    -
     Key: Name
     Value: !Sub "${AWS::StackName}-VPC"
 pubSub:
  Type: AWS::EC2::Subnet
  Properties:
   AvailabilityZone:
    Fn::Select:
     - 0
     - Fn::GetAZs: ""
   CidrBlock: !Ref pubSubnet
   VpcId: !Ref vpcK8S
   Tags:
    -
     Key: Name
     Value: !Sub "${AWS::StackName}-Public-Subnet"
 privSub:
  Type: AWS::EC2:Subnet
  Properties:
   AvailabilityZone:
    Fn::Select:
     - 0
     - Fn::GetAZs: ""
   CidrBlock: !Ref privSubnet
   VpcId: !Ref vpcK8S  
   Tags:
    -
     Key: Name
     Value: !Sub "${AWS::StackName}-Private-Subnet"
Outputs:
 MyRegion:
  Description: My Region Name
  Value: !Ref "AWS::Region"
 VpcId:
  Description: VPC ID Exports
  Value: !Ref vpcK8S
  Exports:
   Name: !Sub "${AWS::StackName}-VPCID"
 PrivateSubnet:
  Description: Private Subnet Exports
  Value: !Ref privSub
  Exports:
   Name: !Sub "${AWS::StackName}-PRIVATE-SUBNET
 PublicSubnet:
  Description: Public Subnet Exports
  Value: !Ref pubSub
  Exports:
   Name: !Sub "${AWS::StackName}-PUBLIC-SUBNET
 PrivateRouteTable:
  Description: Private Route Table Exports
  Value: !Ref privRT
  Exports:
   Name: !Sub "${AWS::StackName}-PRIVATE-RT
 PublicRouteTable:
  Description: Public Route Table Exports
  Value: !Ref pubRT
  Exports:
   Name: !Sub "${AWS::StackName}-PUBLIC-RT

